### ISSUE TITLE
Crash Error use click-odoo

### ISSUE THREAD

**Issue by Solman28** [acsone/click-odoo#20]
Hi,

I used click-odoo from console in a enviroment python3.6, i have odoo11 installed and it shows:

-----

Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/env.py", line 8, in <module>
    import odoo
ModuleNotFoundError: No module named 'odoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/env.py", line 15, in <module>
    import openerp as odoo
ModuleNotFoundError: No module named 'openerp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/bin/click-odoo", line 7, in <module>
    from click_odoo.cli import main
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/__init__.py", line 4, in <module>
    from .env_options import env_options  # noqa
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/env_options.py", line 11, in <module>
    from .env import OdooEnvironment, odoo
  File "/opt/odoo/odoo11-venv/lib/python3.6/site-packages/click_odoo/env.py", line 20, in <module>
    raise ImportError("No module named odoo nor openerp")
ImportError: No module named odoo nor openerp

----

I have to do some configuration?

**Comment by sbidoul** [comment]
Can you check if `python -c "import odoo"` works?

If not, it means Odoo is not correctly installed.

It must be either in your pythonpath or installed with `pip install -e /../the-odoo-source-dir`

**Comment by sbidoul** [comment]
No answer, therefore closing. Feel free to reopen if you think there is an issue with click-odoo.

**Comment by eLBati** [comment]
@sbidoul Hi.
Something similar is happening to me too.
`$ python -c "import odoo"` works.

But:
```
$ click-odoo -h
Traceback (most recent call last):
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/env.py", line 8, in <module>
    import odoo
ImportError: No module named 'odoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/env.py", line 15, in <module>
    import openerp as odoo
ImportError: No module named 'openerp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/bin/click-odoo", line 7, in <module>
    from click_odoo.cli import main
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/__init__.py", line 4, in <module>
    from .env_options import env_options  # noqa
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/env_options.py", line 11, in <module>
    from .env import OdooEnvironment, odoo
  File "/home/elbati/workspace/odoo/instances/odoo12/odoo/lib/python3.5/site-packages/click_odoo/env.py", line 20, in <module>
    raise ImportError("No module named odoo nor openerp")
ImportError: No module named odoo nor openerp
```

**Comment by eLBati** [comment]
This does not happen in virtualenvs where odoo is installed with pip.
I didn't understand this was a requirement.
Keep on testing...

**Comment by sbidoul** [comment]
@eLBati @Solman28 can you please check out #23 ?

**Comment by Solman28** [comment]
Hi @sbidoul I try first with:

**pip install -e /path_odoo**

after this command I see can execute odoo as command from any path por example:

odoo --version
Odoo Server 11.0

Next I try to do : 

click-odoo -d database_name test.py

and it load the odoo's modules, next it execute my script test.py correctly.

Thank you so much, apparently was missing pip install -e /path_odoo
